services:
  bgp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bgp:latest
    container_name: bgp
    security_opt:
      - seccomp:unconfined
    working_dir: /app
    command: tail -f /dev/null
    depends_on:
      - openbgpd
    volumes:
      - .:/app
    networks:
      app_subnet:
        ipv4_address: 172.16.1.3

  openbgpd:
    image: openbgpd/openbgpd:edge
    container_name: openbgpd
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./bgpd/bgpd.conf:/etc/bgpd/bgpd.conf
    networks:
      app_subnet:
        ipv4_address: 172.16.1.4

networks:
  app_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1
