---
name: test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint (OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}})
    strategy:
      matrix:
        otp: ['24']
        elixir: ['1.13']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v1
        env:
          cache-name: mix
        with:
          path: ~/.mix
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.otp }}-${{ matrix.elixir }}
      - uses: actions/cache@v1
        env:
          cache-name: build
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.otp }}-${{ matrix.elixir }}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix credo --strict --all
      - run: mix dialyzer
  test:
    runs-on: ubuntu-latest
    name: Test (OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}})
    strategy:
      matrix:
        otp: ['25', '24', '23', '22']
        elixir: ['1.14', '1.13', '1.12', '1.11']
        exclude:
          - {otp: '25', elixir: '1.13'}
          - {otp: '25', elixir: '1.14'}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v1
        env:
          cache-name: mix
        with:
          path: ~/.mix
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.otp }}-${{ matrix.elixir }}
      - uses: actions/cache@v1
        env:
          cache-name: build
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.otp }}-${{ matrix.elixir }}
      - run: mix deps.get
      - run: mix test
